export const IPC_CHANNELS = {
  listEvents: 'calendar:list-events',
  upsertEvent: 'calendar:upsert-event',
  deleteEvent: 'calendar:delete-event',
  getOutboxCount: 'calendar:get-outbox-count',
  listOutboxJobs: 'calendar:list-outbox-jobs',
  cancelOutboxJob: 'calendar:cancel-outbox-job',
  syncNow: 'calendar:sync-now',
  forcePushAll: 'calendar:force-push-all',
  connectGoogle: 'calendar:connect-google',
  disconnectGoogle: 'calendar:disconnect-google',
  getGoogleConnectionStatus: 'calendar:get-google-connection-status',
  listGoogleCalendars: 'calendar:list-google-calendars',
  getSelectedCalendar: 'calendar:get-selected-calendar',
  setSelectedCalendar: 'calendar:set-selected-calendar',
  getShiftSettings: 'calendar:get-shift-settings',
  setShiftSettings: 'calendar:set-shift-settings',
  getGoogleOAuthConfig: 'calendar:get-google-oauth-config',
  setGoogleOAuthConfig: 'calendar:set-google-oauth-config',
  windowMinimize: 'window:minimize',
  windowMaximize: 'window:maximize',
  windowClose: 'window:close',
  windowMaximizeChanged: 'window:maximize-changed',
  windowViewportCorrection: 'window:viewport-correction',
} as const
